ansible_connection: ssh
ansible_user: ec2-user
ansible_ssh_private_key_file: /root/.ssh/ansible_key
ansible_ssh_common_args: '-o ProxyCommand="aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters portNumber=%p --region eu-west-1" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
