---
- name: Disable Magento 2FA
  hosts: all
  become: true
  remote_user: ec2-user
  vars_files:
    - "../inventory/group_vars/all.yml"
    - "../inventory/group_vars/env_dev.yml"

  tasks:
    - name: Disable TwoFactorAuth module and its dependency
      command: php bin/magento module:disable Magento_AdminAdobeImsTwoFactorAuth Magento_TwoFactorAuth
      args:
        chdir: /var/www/html/magento

    - name: Clear cache
      command: php bin/magento cache:flush
      args:
        chdir: /var/www/html/magento
